---

- name: Check if file exists
  delegate_to: "{{ ownca_delegate_to }}"
  ansible.builtin.stat:
    path: "{{ file_path }}"
  register: __fstat

- name: Decrypt file
  delegate_to: "{{ ownca_delegate_to }}"
  ansible.builtin.command:
    cmd: "ansible-vault decrypt --vault-password-file {{ ownca_vault_password_file }} {{ file_path }}"
  register: __decrypt
  changed_when: __decrypt.rc == 0
  failed_when:
    - __decrypt.rc != 0
    - "'not vault encrypted data' not in __decrypt.stderr"
  when: __fstat.stat.exists
